# WSD Homework

1. Выберите 5 неоднозначных лексем и соберите для них словарные значения (толкования). Можно использовать [МАС](http://feb-web.ru/feb/mas/mas-abc/) или любой другой толковый словарь. Обязательно укажите, каким словарем вы пользовались. - 1 балл за ручной сбор данных, 1 балл за краулинг

Неоднозначные лексемы:
- очки
- сушка
- поток
- замок
- коса

In [1]:
import re, regex

In [2]:
# dictionary entries, gathered manually

with open('dict_entries.txt', 'r') as f:
    entries = f.read()
    
print(*entries.split('\n'), sep='\n\n')

ОЧКО, -о́в, мн.

1. Оптический прибор из двух стекол на дужках, употребляемый при недостатках зрения или для защиты глаз. Очки для близоруких. Защитные очки. □ [Лакей] подал на железном подносе моей бабушке большое письмо с гербовой печатью. Бабушка надела очки, прочла письмо. Тургенев, Пунин и Бабурин. Каждый день чуть не с утра, в очках, с книгой и зонтиком под мышкой, он приходил к нам. Короленко, История моего современника.

2. Спец. Обводы более светлой или темной окраски вокруг глаз у животного. Привел раз мне один мужичок гончую, был это рослый, статный кобель и на глазах очки. М. Пришвин, Анчар.

◊

Сквозь розовые очки смотреть на кого-что см. розовый.

3. Значок на игральной карте или кости, обозначающий ее масть, достоинство в игре.

4. Единица счета при оценке в спортивных соревнованиях, играх. Получить наибольшее количество очков. □ [Школьники] заводили бесконечные игры в войну, в лапту, в чижи на счет до ста очков, в городки на двенадцать фигур. Мусатов, Стожары.

5. Прост

In [3]:
# найдем слова регуляркой
words = [word.lower() for word in re.findall(r'([\w\d]+?), -\w', entries)]
# найдем определения регуляркой
definitions = sum([re.findall(r'^(\d\..+?)$', line) for line in entries.split('\n')], [])
# сделаем словарь
grouped_dfns = dict.fromkeys(words)
i = -1

for dfn in definitions:
#     если счет определений начался с 1, начинаем новый список под новым ключом 
    if dfn.startswith('1'):
        i += 1
        grouped_dfns[words[i]] = []
    grouped_dfns[words[i]].append(dfn)

In [4]:
grouped_dfns

{'очко': ['1. Оптический прибор из двух стекол на дужках, употребляемый при недостатках зрения или для защиты глаз. Очки для близоруких. Защитные очки. □ [Лакей] подал на железном подносе моей бабушке большое письмо с гербовой печатью. Бабушка надела очки, прочла письмо. Тургенев, Пунин и Бабурин. Каждый день чуть не с утра, в очках, с книгой и зонтиком под мышкой, он приходил к нам. Короленко, История моего современника.',
  '2. Спец. Обводы более светлой или темной окраски вокруг глаз у животного. Привел раз мне один мужичок гончую, был это рослый, статный кобель и на глазах очки. М. Пришвин, Анчар.',
  '3. Значок на игральной карте или кости, обозначающий ее масть, достоинство в игре.',
  '4. Единица счета при оценке в спортивных соревнованиях, играх. Получить наибольшее количество очков. □ [Школьники] заводили бесконечные игры в войну, в лапту, в чижи на счет до ста очков, в городки на двенадцать фигур. Мусатов, Стожары.',
  '5. Прост. Род азартной карточной игры; двадцать одно. На

In [51]:
# crawling

import requests
from fake_useragent import UserAgent
from bs4 import BeautifulSoup

import time
import random

from random import randint

session = requests.session()

def get_random_user_agent(user_agent_list):
    random_index = randint(0, len(user_agent_list) - 1)
    return user_agent_list[random_index]

## Retrieve User-Agent List From ScrapeOps
user_agent_list = [
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Windows; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8",
    "Mozilla/5.0 (Windows NT 10.0; Windows; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15",
    "Mozilla/5.0 (Windows NT 10.0; Windows; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36"
  ]

url_list = [
  'https://example.com/1',
  'https://example.com/2',
  'https://example.com/3',
]

with open('errors.txt', 'w') as f:
    pass

# download soup

def get_page(url): 
    
    user_agent = get_random_user_agent(user_agent_list)
    try:
        response = session.get(url, headers={'User-Agent':user_agent})
    except Exception as err:
        with open('errors.txt', 'a') as f:
            f.write(f'{err}\t{url}\n')
        return None
    soup = BeautifulSoup(response.text, 'html.parser')
    time.sleep(random.random())
    
    return soup

In [97]:
# будем краулить словарь ожегова
soup = get_page('https://slovarozhegova.ru/letter.php')
charkods = list(filter(lambda x: 'charkod' in x, [link.findAll('a')[0]['href'] for link in soup.findAll('strong') if link.findAll('a') != []]))
char2charkod = dict(zip(list('абвгдежзийклмнопрстуфхцчшщэюя'), charkods))
base_url = 'https://slovarozhegova.ru/'

In [119]:
def search_dict(word):
    start_char = word[0]
    char_page = get_page('https://slovarozhegova.ru/' + char2charkod[start_char])
    word_urls = list(filter(lambda x: 'word' in x[1] and x[0] == word, 
                            [(line.text.lower(), line['href']) for line in char_page.findAll('a')]))
    dfns = [
        list(filter(lambda x: word in x and len(x) > len(word) * 3, [line.text.lower().strip() for line in 
            get_page(base_url+word_url).findAll('p')]))[0]
        for _, word_url in word_urls
    ]
    return dfns

In [121]:
search_dict('каша')

['каша, -и,  ж. 1.  кушанье из  сваренной или запаренной  крупы.  крутая,густая, жидкая к.  гречневая,  пшенная,  рисовая,  манная к.  заварить  кашукипятком.  маслом  каши не  испортишь (посл.). мало каши ел  (перен.: молод,неопытен или  недостаточно силен; разг.  ирон.). 2. перен. то же, что месиво(в  1 знач.) (разг.). к.  из песка и снега. 3. нечто беспорядочное, путаница(разг.). к. в голове у кого-н. к. в изложении.* каши не сваришь с кем (разг.неодобр.) - не  сговоришься, не сделаешь дела с кем-н. каши просят (ботинки,сапоги)  (разг. шутл.) - износились до дыр. каша во рту у  кого  (разг.) - отом,  кто  говорит неясно, нечетко. заварить кашу (разг. неодобр.) - затеятьхлопотливое дело. расхлебать кашу  (разг. неодобр.)  - распутать хлопотливоедело. заварили кашу, а я расхлебывай. ii умвньш. кашка, -и, ж. (к 1 знач.).']

In [122]:
crawled_dfns = [search_dict(word) for word in words]

In [125]:
words

['очко', 'мука', 'поток', 'замок', 'коса']

In [123]:
# слова очко в словаре Ожегова нет
crawled_dfns

[[],
 ['мука,  -и,  ж.  сильное  физическое  или  нравственное страдание.  мукиголода.   муки  одиночества.  муки   творчества.  муки   слова  (о   тяжестиписательского  труда). хождение по мукам (ряд  тяжелых жизненных испытаний).не жизнь, а м, м. мученическая (о сильной муке, мучении; разг.).',
  'мука,  -и,  ж. 1. размолотые в  порошок зерна.  м.  ржаная,  пшеничная,гречневая,  ячневая,  кукурузная,  соевая, гороховая.  2.  размолотые  зернапшеницы или ржи. м. высшего сорта. м.-крупчатка. ларь для  муки. 3.  порошокиз  какого-н.  измельченного  вещества.  травяная  мука  (кормовая  добавка:измельченная  сухая  трава).   костная  м.  рыбная   м.  (кормовая  добавка:измельченная сушеная рыба и отходы ее  переработки). ii уменьш. мучка, -и,ж.(также спец.) и  мучица,  -ы,  ж. рисовая мучка  (отходы обработки риса). iiприл. мучной, -ая, -ое. м. мешок (для муки).'],
 ['поток, -а, м. 1. стремительно текущая водная масса. бурный п. горный п.глубинный  п.  (подводное  течение).  2. движущаяс

Я уже нашла определения руками и сделала с ними тетрадку, так что накрауленные пусть будут просто так.

2. Выберите один или несколько корпусов [коллекции Corus](https://github.com/natasha/corus#reference), извлеките оттуда все предложения, где содержатся ваши неоднозначные слова. - 1 балл

In [5]:
import pandas as pd
import numpy as np

# скачаем корпус
corpus = pd.read_csv('./lenta-ru-news.csv')

<ipython-input-5-e820022f6a46>:4: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  corpus = pd.read_csv('./lenta-ru-news.csv')


In [6]:
# оставим нужное
corpus = corpus[['title', 'text']].dropna()
# приведем к нижнему регистру
corpus.title = corpus.title.apply(lambda x: str(x).lower())
corpus.text = corpus.text.apply(lambda x: str(x).lower())

In [7]:
corpus.head()

title  \
0  1914. русские войска вступили в пределы венгрии     
1  1914. празднование столетия м.ю. лермонтова от...   
2                           1914. das ist nesteroff!   
3                    1914. бульдог-гонец под льежем    
4           1914. под люблином пойман швабский зверь   

                                                text  
0  бои у сопоцкина и друскеник закончились отступ...  
1  министерство народного просвещения, в виду про...  
2  штабс-капитан п. н. нестеров на днях, увидев в...  
3  фотограф-корреспондент daily mirror рассказыва...  
4  лица, приехавшие в варшаву из люблина, передаю...

In [8]:
from pymorphy2 import MorphAnalyzer

# пригодится для лемматизации
morph = MorphAnalyzer()

In [9]:
morph.parse('сосиска')[0].normal_form

'сосиска'

In [10]:
subcorps = []
word_col = []

# будем искать слова в текстах
for word in words:
    subcorp = corpus.loc[corpus.text.str.contains(morph.parse(word.strip('123'))[0].normal_form)]
    print(word, len(subcorp), sep='\t')
    subcorps.append(subcorp)
    word_col.extend([word.lower()] * len(subcorp))
    
df = pd.concat(subcorps)
# запишем, где какое было
# в корпусе будут повторения, если окажется, что какие-то 2+ слова встретились в одном тексте. думаю, это не важно
df['word'] = word_col

очко	13468
мука	679
поток	8508
замок	749
коса	5045


In [11]:
df.shape

(28449, 3)

In [12]:
df.sample(10)

title  \
553460  в сбу назвали число скрывающихся под мукачево ...   
105505  абрамович может купить принадлежащие "юкосу" а...   
469509       сборные южной кореи и ирана вышли на чм-2014   
452342  в сборную россии по хоккею вызвали семь игроко...   
226311  команда кириленко одержала вторую победу в сер...   
530430  количество отдыхающих в крыму россиян возросло...   
139172  мосгорсуд подтвердил санкцию на арест адвоката...   
282611               лидер "зенита" пропустит матч с цска   
376638          испания решила засудить гамбург за огурцы   
550294  искусственный интеллект прошел уровень в игре ...   

                                                     text   word  
553460  в районе города мукачево закарпатской области ...   мука  
105505  басманный суд москвы наложил арест на акции "с...   коса  
469509  сборные южной кореи и ирана по футболу вышли н...   очко  
452342  главный тренер сборной россии по хоккею зинэту...   очко  
226311  "юта джаз", в составе которой выступает россий...   очко  
530430  в 2014 году в крыму отдохнули более 4 миллионо...  поток  
139172  мосгорсуд признал законной выдачу заочной санк...   коса  
282611  лидер питерского "зенита" данни, 14 мая получи...   очко  
376638  правительство испании намерено потребовать от ...   очко  
550294  программист продемонстрировал работу искусстве...   очко

In [13]:
# сохраним фильтрованный корпус
df.to_csv('filtered_corpus.csv')

In [14]:
# lemmatize and remove puctuation for adagram
import nltk
nltk.download("stopwords")

from nltk.corpus import stopwords
from string import punctuation
from pymystem3 import Mystem

#Create lemmatizer and stopwords list
mystem = Mystem() 
russian_stopwords = stopwords.words("russian")

def preprocess_text(text):
    tokens = mystem.lemmatize(text.lower())
    tokens = [token for token in tokens if token not in russian_stopwords\
              and token != " " \
              and token.strip() not in punctuation]
    
    text = " ".join(tokens)
    
    return text

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/shikunova/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [15]:
preprocess_text('люблю курицу с лапшой')

'любить курица лапша'

In [ ]:
# препроцессим текст для AdaGram
texts = df.text.apply(preprocess_text)

In [ ]:
# сохраняем
with open('tokenized.txt', 'w') as f:
    f.write(' '.join(texts))

Разбейте полученные контексты по значениям двумя любыми способами (вы можете использовать способы с семинара, заменить там эмбеддинги, реализовать какой-то свой способ). Напоминалка: в случае с AdaGram вы сразу получаете какой-то номер значения, с ELMo и другими контекстуальными эмбеддингами — нужно кластеризовать. - 2 балла

In [16]:
import pandas as pd
df = pd.read_csv('filtered_corpus.csv')

## AdaGram

In [17]:
!pip install Cython numpy
!pip install git+https://github.com/lopuhin/python-adagram.git

  Cloning https://github.com/lopuhin/python-adagram.git to /private/var/folders/mw/9414n2bj3bn4xwh4p6qqjhdh0000gn/T/pip-req-build-t8rzkiw6
  Running command git clone -q https://github.com/lopuhin/python-adagram.git /private/var/folders/mw/9414n2bj3bn4xwh4p6qqjhdh0000gn/T/pip-req-build-t8rzkiw6


In [18]:
# обучение модели на нашем корпусе
!adagram-train tokenized.txt out.pkl # training finished

In [19]:
import adagram
vm = adagram.VectorModel.load('out.pkl')

In [20]:
for word in words:
#     напечатаем слово и все отдельные значения, которые нашел AdaGram
    print(word, vm.word_sense_probs(word), sep='\t')
    print()
    for i in range(len(vm.word_sense_probs(word))):
        print(*vm.sense_neighbors(word, i), sep='\n')
        print()
    print('=======================================\n')

очко	[(0, 0.9998840041758497)]

('актив', 1, 0.59554255)
('квартет', 0, 0.5678568)
('таблица', 0, 0.53796685)
('набирать', 0, 0.49799982)
('35', 0, 0.49188212)
('место', 0, 0.47337472)
('очки', 0, 0.46855336)
('очки', 1, 0.45818347)
('дивизион', 0, 0.45786032)
('иметь', 0, 0.44721916)


мука	[(0, 0.999694283093855)]

('растительный', 0, 0.8709951)
('велком', 0, 0.8568457)
('шкура', 0, 0.85079354)
('свиной', 0, 0.839448)
('останкино', 0, 0.8392174)
('крахмал', 0, 0.8360104)
('рублевский', 0, 0.8323663)
('шкурка', 0, 0.8323056)
('ркк', 0, 0.8321657)
('инерция', 0, 0.83063054)


поток	[(0, 0.2238976465873991), (1, 0.7760946244720198)]

('горячо', 0, 0.45386723)
('экспортироваться', 0, 0.4368371)
('133', 0, 0.41999313)
('эксплуатировать', 0, 0.41217166)
('рост', 0, 0.40720397)
('wave', 0, 0.39971697)
('rwe', 0, 0.39530843)
('немногое', 0, 0.38286093)
('объем', 0, 0.3796735)
('составлять', 0, 0.37861094)

('денежный', 0, 0.59043723)
('увеличение', 0, 0.5055098)
('капитальный', 0, 0.43758988

## BERT

In [21]:
from transformers import BertModel, BertTokenizer

# маленький берт
model = BertModel.from_pretrained('cointegrated/rubert-tiny2',
           output_hidden_states = True,)
tokenizer = BertTokenizer.from_pretrained('cointegrated/rubert-tiny2', model_max_length=2048)

In [23]:
# источник https://medium.com/mlearning-ai/getting-contextualized-word-embeddings-with-bert-20798d8b43a4
def bert_text_preparation(text, tokenizer):
    marked_text = "[CLS] " + text + " [SEP]"
    tokenized_text = tokenizer.tokenize(marked_text)[:2048] # truncate to fit into the model's context
    indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
    segments_ids = [1]*len(indexed_tokens)
    # convert inputs to tensors
    tokens_tensor = torch.tensor([indexed_tokens])
    segments_tensor = torch.tensor([segments_ids])
    return tokenized_text, tokens_tensor, segments_tensor

def get_bert_embeddings(tokens_tensor, segments_tensor, model):
    """
    Obtains BERT embeddings for tokens.
    """
    # gradient calculation id disabled
    with torch.no_grad():
        # obtain hidden states
        outputs = model(tokens_tensor, segments_tensor)
        hidden_states = outputs[2]
    # concatenate the tensors for all layers
    # use "stack" to create new dimension in tensor
    token_embeddings = torch.stack(hidden_states, dim=0)
    # remove dimension 1, the "batches"
    token_embeddings = torch.squeeze(token_embeddings, dim=1)
    # swap dimensions 0 and 1 so we can loop over tokens
    token_embeddings = token_embeddings.permute(1,0,2)
    # intialized list to store embeddings
    token_vecs_sum = []
    # "token_embeddings" is a [Y x 12 x 768] tensor
    # where Y is the number of tokens in the sentence
    # loop over tokens in sentence
    for token in token_embeddings:
    # "token" is a [12 x 768] tensor
    # sum the vectors from the last four layers
        sum_vec = torch.sum(token[-4:], dim=0)
        token_vecs_sum.append(sum_vec)
    return token_vecs_sum

In [24]:
import pandas as pd
import numpy as np
import torch
from tqdm import tqdm

sample = df         #df.sample(1_000)
sentences = sample.text.tolist()

from collections import OrderedDict

context_embeddings = []
context_tokens = []
vectors = OrderedDict()
contexts = OrderedDict()


for sentence in tqdm(sentences):
    try:
#         токенизация
        tokenized_text, tokens_tensor, segments_tensors = bert_text_preparation(sentence, tokenizer)
#         возьмем эмбеддинги
        list_token_embeddings = get_bert_embeddings(tokens_tensor, segments_tensors, model)
        tokens = OrderedDict()
        for token in tokenized_text[1:-1]:
            if token in tokens:
                tokens[token] += 1
            else:
                tokens[token] = 1
            if token in words:
#                 будем сохранять вхождения нужных нам слов
                if token not in vectors:
                    vectors[token] = []
                    contexts[token] = []
#                 на случай, если токен встречается несколько раз
                token_indices = [i for i, t in enumerate(tokenized_text) if t == token]
                current_index = token_indices[tokens[token] - 1]
                token_vec = list_token_embeddings[current_index]
#                     сохраним вектор
                vectors[token].append(token_vec)
#                     сохраним контекст
                contexts[token].append(sentence)
    except:
#         чтоб не упало из-за какой-нибудь ошибки
        print(sentence)
        continue

100%|██████████| 28449/28449 [37:56<00:00, 12.49it/s]   


In [28]:
for word in vectors:
#     сохраняемся
    torch.save(torch.stack(vectors[word]), f'bert_vectors/{word}.pt')

In [29]:
for word in vectors:
    print(word, len(vectors[word]))

очко 2234
поток 6139
замок 1000
мука 736
коса 1531


In [31]:
word_idcs = []

for word in words:
    tokenized_text, tokens_tensor, segments_tensors = bert_text_preparation(word, tokenizer)
    print(tokenized_text)

['[CLS]', 'очко', '[SEP]']
['[CLS]', 'мука', '[SEP]']
['[CLS]', 'поток', '[SEP]']
['[CLS]', 'замок', '[SEP]']
['[CLS]', 'коса', '[SEP]']


In [32]:
# from sklearn.cluster import DBSCAN
# import numpy as np

# # работает так себе
# for word in words:
#     X = torch.stack(vectors[word]).numpy()
#     clustering = DBSCAN(eps=3, min_samples=2).fit(X)
#     print(np.unique(clustering.labels_))

In [33]:
from sklearn.cluster import KMeans
import numpy as np

cluster_centers = []
word_labels = []

for i, word in enumerate(words):
    try:
#         кластеризуем векторы отдельного слова
        X = torch.stack(vectors[word]).numpy()
#         берем столько кластеров, сколько значений в словаре
        kmeans = KMeans(n_clusters=len(grouped_dfns[word]), random_state=0).fit(X)
        print(word)
        print(kmeans.labels_)
#         сохраним средние векторы и лейблы кластеров
        cluster_centers.append(kmeans.cluster_centers_)    
        word_labels.append(kmeans.labels_)
    except:
        continue

очко
[1 3 4 ... 3 0 4]
мука
[2 1 1 1 2 2 2 2 2 2 0 2 0 1 2 2 1 2 2 2 1 2 0 0 1 1 0 1 1 1 2 1 2 1 0 1 1
 2 2 2 1 2 1 1 0 2 0 2 1 2 2 0 1 2 2 1 1 1 2 1 1 0 2 1 1 2 1 1 0 2 0 1 2 0
 1 2 0 0 1 1 1 1 2 2 1 0 2 2 2 0 2 2 2 1 1 2 1 0 0 1 2 1 2 0 0 1 1 2 0 2 0
 0 1 1 1 2 0 1 2 0 0 0 0 1 2 1 0 1 2 1 2 2 1 2 1 2 1 2 0 1 0 0 2 0 2 1 2 1
 1 1 1 0 2 1 2 1 2 2 0 2 0 0 1 1 2 1 1 0 2 2 1 2 2 1 2 1 0 2 0 2 2 1 1 0 0
 1 1 1 1 0 0 1 1 2 0 0 2 2 1 0 0 1 2 2 0 2 2 1 2 1 2 1 2 2 0 0 1 2 1 1 1 0
 1 2 1 1 2 2 1 2 1 2 0 0 2 2 1 1 1 1 0 2 2 2 2 2 0 1 2 2 1 1 2 2 0 2 2 2 1
 2 1 1 2 1 0 1 1 0 2 0 0 0 1 2 2 0 1 2 1 0 2 1 0 1 0 1 0 1 0 2 1 0 2 1 0 2
 2 2 2 1 0 0 2 0 0 2 2 2 0 2 0 2 2 2 2 0 1 2 1 0 2 2 2 1 2 0 2 1 0 0 0 1 2
 0 0 1 2 1 2 2 0 1 0 2 0 1 1 2 2 2 2 1 1 2 2 2 2 0 2 0 2 2 1 2 0 1 2 2 1 0
 0 0 0 2 0 0 2 0 0 0 0 2 0 0 1 0 2 2 1 0 0 2 2 1 0 1 0 1 0 2 0 1 1 0 0 0 0
 2 0 0 0 2 0 1 2 1 2 1 0 0 1 0 0 2 0 1 1 0 2 1 1 0 0 0 1 1 2 0 0 1 0 2 0 0
 0 0 0 0 0 2 2 1 1 0 2 1 0 0 0 2 1 0 0 0 0 0 2 1 0 0 0 2 0 1 0 2 1 0 1 1

4. Возьмите словарные толкования для каждого значения и припишите им значение автоматически
теми же способами, что и в п.2. - 1 балл

In [34]:
# лемматизация для AdaGram
definitions_lemm = dict([(word, [preprocess_text(dfn) for dfn in dfns]) for word, dfns in grouped_dfns.items()])

In [35]:
adagram_def_vectors = [
    np.stack([vm.sense_vector(word, 0) for word in definition_lemm.split() if word in vm.dictionary.id2word]).mean(axis=0)
               for definition_lemm in sum(list(definitions_lemm.values()), [])
]

In [36]:
adagram_def_vectors[0].shape

(100,)

In [128]:
for word, dfns in definitions_lemm.items():
#         выведем, к какому смыслу модель относит определение
    for dfn in dfns:
        print(dfn)
        print('\t', word)
        print('\t', vm.disambiguate(word, dfn).round(2))
        print('\n==============================\n')

1 оптический прибор стекло дужка употреблять недостаток зрение защита глаз очки близорукий защитный очки □ лакей подавать железный поднос бабушка большой письмо гербовый печать бабушка надевать очки прочитывать письмо тургенев пунин бабурин каждый день утро очки книга зонтик мышка приходить короленко история современник
	 очко
	 [1. 0. 0. 0. 0.]


2 спец обвод светлый темный окраска вокруг глаз животное приводить мужичок гончий это рослый статный кобель глаз очки м пришвин анчар
	 очко
	 [1. 0. 0. 0. 0.]


3 значок игральный карта кость обозначать масть достоинство игра
	 очко
	 [1. 0. 0. 0. 0.]


4 единица счет оценка спортивный соревнование игра получать большой количество очко □ школьник заводить бесконечный игра война лапта чиж счет сто очки городки двенадцать фигура мусатов стожар
	 очко
	 [1. 0. 0. 0. 0.]


5 простой род азартный карточный игра двадцать стол появляться колода карта водиться играть  « очко » соколов микит танакино счастие
	 очко
	 [1. 0. 0. 0. 0.]


6 спец небольш

/Users/shikunova/opt/anaconda3/lib/python3.8/site-packages/adagram/model.py:171: RuntimeWarning: divide by zero encountered in log
  z = np.log(z)


In [38]:
bert_def_vectors = dict([       
    (word, [torch.stack(get_bert_embeddings(*bert_text_preparation(dfn, tokenizer)[1:], model)).mean(0) for dfn in dfns])
        for word, dfns in grouped_dfns.items()
])

In [39]:
(bert_def_vectors['очко'])

[tensor([-3.6683e-01,  6.4928e-01,  3.0449e-01, -4.7502e+00, -7.1839e-01,
          1.3272e+00,  5.4387e-01, -1.6247e+00, -1.5584e+00,  1.0475e-01,
          5.5736e-01,  1.1466e-01, -1.5050e-01,  2.4104e+00,  5.1476e-01,
         -2.0615e+00,  1.9852e+00, -1.4134e+00, -6.2940e-01,  1.8936e+00,
         -1.5246e-01,  7.4789e-01, -7.0214e-01,  1.1467e-01,  3.2362e+00,
          2.3291e+00, -1.4261e+00,  1.5104e+00, -6.5752e-01, -1.5156e+00,
         -6.1523e-01, -7.6945e-01, -5.9495e-01,  4.4407e-01, -1.0105e+00,
         -3.1138e-01,  1.3964e+00, -1.2670e+00,  3.5265e+00, -1.6909e+00,
         -1.9747e+00, -3.1907e-01,  1.1555e+00, -1.0077e+00, -3.8731e-01,
          1.9835e+00,  1.0159e+00, -6.6069e-01, -1.2160e+00, -2.5930e-01,
          1.3362e+00, -2.6617e+00, -1.4865e+00,  8.8396e-01,  4.9210e-01,
         -1.6707e+00, -3.2260e-01, -6.0091e-01, -2.2538e-01, -9.7217e-01,
         -2.2001e+00,  7.2337e-01,  1.3494e+00, -3.1668e+00, -5.8484e-01,
         -1.1420e-01, -1.0558e+00, -1.

In [41]:
for i, word in enumerate(words):
    try:
#         куда модель относит определения? к какому кластеру?
        X = torch.stack(vectors[word]).numpy()
        kmeans = KMeans(n_clusters=len(grouped_dfns[word]), random_state=0).fit(X)
        print(word)
        print('definitions')
        print(kmeans.predict(torch.stack(bert_def_vectors[word]).numpy()))
        print('================================\n')
    except:
        continue

очко
definitions
[4 4 0 4 0 4 1]

мука
definitions
[2 0 2]

поток
definitions
[1 1 3 3]

замок
definitions
[5 5 1 1 1 1]

коса
definitions
[1 1 1 1]



5. Выберите по 2-3 значения для слова и по 5 контекстов, которые автоматически были отнесены к этим значениям. Разметьте контексты: совпадает ли значение слова в контексте со словарным значением. - 1 балл

Здесь я бы сказала что качество 0

In [42]:
grouped_dfns['поток']

['1. Стремительно текущая река, ручей. Весенние потоки. □ В сугробах снежных перед нею Шумит, клубит волной своею Кипучий, темный и седой Поток, не скованный зимой. Пушкин, Евгений Онегин. А по ущелью, во тьме и брызгах, поток стремился навстречу морю, гремя камнями. М. Горький, Песня о Соколе. || чего или какой. Стремительно льющаяся масса чего-л. жидкого. Потоки лавы извергающегося вулкана. □ Приближаясь к главному оврагу, --- охотники увидали шумный поток дождевой воды, несшийся по оврагу сплошной массой. Н. Успенский, Сельский портной. Стоит задеть стволом ружья --- ветку, и холодный поток воды с головы до ног окатывает озябшего, усталого путешественника. Соколов-Микитов, Над синей тайгой. || чего или какой. Распространяющаяся, устремляющаяся в каком-л. направлении масса (воздуха, света, звуков и т. п.). Воздушный поток. Использование потока солнечной энергии. □ Два сильных рефлектора кидали нам в лицо потоки яркого света. Гаршин, Надежда Николаевна. || перен.; чего или какой. Что-

In [43]:
words

['очко', 'мука', 'поток', 'замок', 'коса']

In [45]:
# BERT

labels = word_labels[2]

for sense in np.unique(labels)[:2]:
    print(sense)
    print(*np.stack(contexts['поток'])[labels == sense][:5], sep='\n\n')
    print('==================================\n')

0
в находке убит генеральный директор порта "восточный" леонид бочков. в понедельник около 12:30 по московскому времени возле здания управления порта в бочкова дважды выстрелили из пистолета тт. на место преступления выехала следственно-оперативная бригада прокуратуры приморского края. по подозрению в убийстве уже задержаны четыре человека в возрасте от 20 до 32 лет. все они - жители находки. по одной их версий, преступление связано с переделом собственности (не так давно акции порта приобрела компания "северсталь"). однако, как заявили "стране.ru" заместитель леонида бочкова владимир дудко, председатель совета директоров порта геннадий жебелев и мэр города виктор гнездилов, это предположение безосновательно. по информации "страны.ru", крупнейшим акционером порта является "северсталь" (33 процента), 20 процентов в собственности у государства, еще 35 процентов находятся по доверенности у жебелева. как заявил "интерфаксу" гендиректор "северстали" константин николаев, это преступление "вы

BERT отнес к 1 толкованию определения "поток воды" и "стремительно движущаяся масса", и под лейблом 1 оказались в целом подходящие тексты, только в них _поток_ используется скорее метафорически

значение 0: 0/5
значение 1: 5/5

accuracy .5

In [46]:
# AdaGram

meanings = []
for sentence in sample.loc[sample.word == 'поток', 'text']:
    meanings.append(np.argmax(vm.disambiguate(word, sentence)))

/Users/shikunova/opt/anaconda3/lib/python3.8/site-packages/adagram/model.py:171: RuntimeWarning: divide by zero encountered in log
  z = np.log(z)


In [47]:
np.unique(meanings)

array([0])

AdaGram везде ставит одинаковое значение, что дает нам столько аккураси, сколько в нашей выборке нулевого класса -- допустим, .5, если я взяла 2 значения, включая нулевое.

Если сравнивать BERT и AdaGram, один не лучше другого: оба в случае, где надо разграничить два смысла, выдают для всех один лейбл и в лучшем случае достигают .5 accuracy. Проверим еще на слове _коса_:

In [48]:
# BERT

labels = word_labels[-1]

for sense in np.unique(labels)[:2]:
    print(sense)
    print(*np.stack(contexts['коса'])[labels == sense][:5], sep='\n\n')
    print('==================================\n')

0
россия отказалась от планов поставки зенитных ракетных комплексов с-300 ирану. об этом, как сообщает "интерфакс", заявил начальник генерального штаба вооруженных сил россии николай макаров. по его словам, такое решение было принято в связи с санкциями оон, введенными в отношении ирана 9 июня 2010 года. при этом макаров не дал однозначного ответа на вопрос, будет ли разорван соответствующий контракт на поставку с-300. 15 июля 2010 года генеральный директор госкорпорации "ростехнологии" сергей чемезов объявил, что решение об аннулировании контракта с ираном может быть принято только президентом россии. "пока контракт не аннулирован", - отметил тогда чемезов. следует отметить, что долгое время не было точно известно, коснутся ли новые санкции оон поставок с-300 ирану. в начале июня 2010 года глава комитета госдумы по международным делам константин косачев и директор федеральной службы по военно-техническому сотрудничеству михаил дмитриев заявили, что исполнение контракта с ираном будет 

Здесь виден один из недостатков берта: WordPiece токенизатор тут мешает, потому что наша _коса_ попала внутрь фамилий, упоминающихся в публикациях. AdaGram таким не страдает (но все равно везде ставит одинаковое значение):

In [49]:
# AdaGram

meanings = []
for sentence in sample.loc[sample.word == 'коса', 'text']:
    meanings.append(np.argmax(vm.disambiguate(word, sentence)))

In [50]:
np.unique(meanings)

array([0])